### ISSUE TITLE
In Moodle 4.1 können keine Fragen aus der Fragensammlung hinzugefügt werden

### ISSUE THREAD

**Issue by stefan-weber-think-modular** [elearning-univie/moodle-mod_flashcards#2]
Moodle 4.1.10 (Build: 20240422) 
mod_flashcards v4.4.1 (2024010101)

Problem konnte in Moodle 4.4 nicht reproduziert werden.

## Reproduce

- Activity anlegen
- Neue Lernkarte anlegen
- Frage aus der Fragensammlung hinzufügen
 
![image](https://github.com/user-attachments/assets/600546c1-27c3-421a-ab74-6d7487e46792)

Nichts passiert:

![image](https://github.com/user-attachments/assets/91cd5af4-b356-4163-a936-214da7912ad5)

Falls Moodle 4.1 nicht mehr unterstützt wird, bitte $plugin->requires anpassen.

**Comment by mwreichel** [comment]
Hi,

thanks for reporting this.
You're right. In this case we have to update the required version for 4.4 due to some changes using the question bank.
Please use the stable-branch for 4.3 instead, this should work.

Cheers,
Martin ;-)

**Comment by stefan-weber-think-modular** [comment]
hi martin,

unfortunately, branch MOODLE_403_STABLE has the same problem on Moodle 4.1 for me. do you know what could be the last commit that works on 4.1?

**Comment by mwreichel** [comment]
hi,
yes, you're right. we checked it.
unforunately we have to look up in history, when we finished work for moodle 4.1 in the past (due to the beta-status we didn't prepared a stable-version for 4.1). we will prepare this for you...

**Comment by aczerzuh** [comment]
Hey, i created the branch MOODLE_401_STABLE and checked the code briefly in Moodle 4.1 and it should run. If you run into any other problems just let us know.
cheers adrian

**Comment by stefan-weber-think-modular** [comment]
@aczerzuh unfortunately, i run into the same problem that i do with the latest version - i cannot add a question from the question bank - nothing happens but a JS error

![image](https://github.com/user-attachments/assets/15eb5976-18f7-469d-9878-03e4f2491e8d)

**Comment by aczerzuh** [comment]
Please double check in the plugins overview that the version v4.2.1 (2023042401) is installed and just in case maybe clear the cache. I do get the same error with our latest version but with the one in the MOODLE_401_STABLE branch it is working on my Moodle 4.1.14 version.
![image](https://github.com/user-attachments/assets/d75e93ab-6325-4ada-ab25-da8b436bff87)
![image](https://github.com/user-attachments/assets/21df25fb-dd18-4bd5-8c9d-64803b47fc05)
![image](https://github.com/user-attachments/assets/af5ae8cc-d183-4586-ad97-074b4349826e)

**Comment by stefan-weber-think-modular** [comment]
@aczerzuh my bad, updated the wrong test server, it does indeed work! thanks a lot :)
